#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 paulr@sdf.org -- part of Copal Linux.
#
# build-gallery.py -- write docs/gallery.html from whatever is in docs/media.
#
# WHY GENERATED RATHER THAN HAND-WRITTEN. The media is regenerated by
# `make release`, and a hand-maintained gallery would list images that the
# next capture renamed, removed or never produced. Generating it from the
# directory means the page cannot claim a screenshot that is not there, and a
# new screenshot appears in it without anybody remembering to add a figure.
#
# The captions are the part a directory listing cannot supply, so they live in
# CAPTIONS below, keyed by filename. An image with no caption still appears --
# unlabelled is better than absent, and it is the prompt to add one.

import html
import pathlib
import sys

MEDIA = pathlib.Path("docs/media")
OUT = pathlib.Path("docs/gallery.html")

# Video counts as media. It is the same recording as the GIF, so it belongs in
# the gallery rather than hidden in the repository -- somebody who wants to
# scrub through the install should not have to go looking for it.
IMG_EXT = {".png", ".gif", ".jpg", ".jpeg", ".webp"}
VID_EXT = {".mp4", ".webm"}


def media_tag(name, title, present):
    """An <img> or a <video>, decided by the file rather than by a flag."""
    if present[name].suffix.lower() in VID_EXT:
        return (f'<video src="media/{html.escape(name)}" controls '
                'preload="metadata" playsinline></video>')
    return (f'<img src="media/{html.escape(name)}" '
            f'alt="{html.escape(title)}" loading="lazy">')

# Ordered: the gallery reads as the install does, start to finish. Anything
# not named here is appended at the end in filename order.
CAPTIONS = [
    ("release-pipeline.gif", "make release, start to finish",
     "The Mac side: purge, build, verify, record, render, regenerate. Six "
     "minutes of pipeline at 6x. The verify step is the one that can stop it."),
    ("install-cast.gif", "The install, accelerated",
     "Sixteen stages recorded from the VM's serial console. Every command is "
     "printed before it runs, and each phase is timed."),
    ("guided-levels.gif", "Choosing a level",
     "The first screen on a card that has never been set up: server, medium, "
     "or the full monty."),
    ("antiquity-desktop.png", "Hyprland, themed as Linux Antiquity",
     "The full level. Workspaces are planets on an orbital curve; the power "
     "menu is three tarot cards."),
    ("i3-desktop.png", "i3 on the framebuffer",
     "The medium level — the desktop that fits a Pi Zero, recoloured to the "
     "same palette so switching session changes the compositor, not the look."),
    ("install.mp4", "The same install, as video",
     "For scrubbing and pausing. The GIF above is the same frames, encoded "
     "for a page rather than for a player."),
    ("screen-1.png", "First frame after boot",
     "Taken by QEMU's monitor: the guest's own framebuffer, at the guest's "
     "own resolution."),
]

PAGE_HEAD = """<title>Copal Gallery</title>
<meta name="description" content="Screenshots and recordings of Copal Linux installing and running — captured from real installs, not mocked up.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400&family=JetBrains+Mono:wght@400;700&display=swap">
<style>
/* The palette and the plate shadows are docs/index.html's, deliberately: a
   gallery that looked like a different site would undo the point of it. See
   the long note at the top of that file for why black is the key and not the
   field. */
:root {
  --paper:        #f2e3c0;
  --paper-raised: #fce2ab;
  --paper-deep:   #e7d5a6;
  --paper-edge:   #dcc793;
  --ink-key:      #121212;
  --ink-body:     #1b1710;
  --ink-dim:      #6d6047;
  --gold:         #8a6320;
  --resin-deep:   #87704f;
  color-scheme: light;
}
*, *::before, *::after { box-sizing: border-box; }
body {
  margin: 0; padding: 0 1.25rem 6rem;
  background: var(--paper); color: var(--ink-body);
  font: clamp(.9rem, .86rem + .18vw, 1rem)/1.65 "JetBrains Mono", ui-monospace, Menlo, monospace;
}
main { max-width: 68rem; margin: 0 auto; }
header { padding: 4rem 0 1rem; }
h1 {
  font-family: "Cormorant Garamond", Georgia, serif; font-weight: 300;
  font-size: clamp(2.4rem, 8vw, 4rem); line-height: 1; margin: 0 0 .75rem;
  color: var(--ink-key);
}
.sub { color: var(--ink-dim); max-width: 60ch; margin: 0 0 1rem; }
a { color: var(--gold); text-underline-offset: .2em; }
a:hover { color: var(--ink-key); }
.back {
  display: inline-block; margin-bottom: 2.5rem; font-size: .82rem;
  letter-spacing: .1em; text-transform: uppercase;
}
.grid {
  display: grid; gap: 2rem;
  grid-template-columns: repeat(auto-fit, minmax(21rem, 1fr));
}
figure { margin: 0; display: flex; flex-direction: column; gap: .7rem; }
/* The frame is the plate: black key line, hard offset shadow, no blur. */
.frame {
  border: 1px solid var(--ink-key); background: var(--paper-deep);
  box-shadow: 5px 5px 0 var(--paper-edge); overflow: hidden;
}
.frame img, .frame video { display: block; width: 100%; height: auto; }
figcaption { font-size: .82rem; color: var(--ink-dim); }
figcaption b { display: block; color: var(--ink-body); font-weight: 700;
               font-size: .88rem; margin-bottom: .15rem; }
figcaption .file {
  display: block; margin-top: .35rem; font-size: .7rem;
  color: var(--resin-deep); letter-spacing: .04em;
}
.empty {
  border: 1px dashed var(--resin-deep); padding: 2rem; text-align: center;
  color: var(--ink-dim); font-size: .85rem;
}
footer {
  margin-top: 4rem; padding-top: 1.5rem; border-top: 1px solid var(--ink-key);
  font-size: .78rem; color: var(--ink-dim);
}
</style>
"""


def main() -> int:
    if not MEDIA.is_dir():
        print("build-gallery: no docs/media", file=sys.stderr)
        return 1

    present = {p.name: p for p in sorted(MEDIA.iterdir())
               if p.suffix.lower() in IMG_EXT | VID_EXT}

    ordered, seen = [], set()
    for name, title, blurb in CAPTIONS:
        if name in present:
            ordered.append((name, title, blurb))
            seen.add(name)
    for name in present:
        if name not in seen:
            ordered.append((name, name, ""))

    parts = [PAGE_HEAD, "<main>\n<header>\n",
             "<h1>Copal, photographed</h1>\n",
             '<p class="sub">Every image here came out of a real install — the '
             "recordings from the VM's serial console, the screenshots from "
             "QEMU's own framebuffer. Nothing is a mock-up and nothing was "
             "taken with a camera.</p>\n",
             '<a class="back" href="./">← back to Copal</a>\n</header>\n']

    if not ordered:
        parts.append('<p class="empty">No media yet. Run <code>make release</code>.</p>\n')
    else:
        parts.append('<div class="grid">\n')
        for name, title, blurb in ordered:
            size = present[name].stat().st_size
            kb = f"{size / 1024:.0f} kB" if size < 1024 * 1024 else f"{size / 1048576:.1f} MB"
            parts.append(
                "  <figure>\n"
                f'    <div class="frame">{media_tag(name, title, present)}</div>\n'
                "    <figcaption>\n"
                f"      <b>{html.escape(title)}</b>{html.escape(blurb)}\n"
                f'      <span class="file">{html.escape(name)} · {kb}</span>\n'
                "    </figcaption>\n"
                "  </figure>\n")
        parts.append("</div>\n")

    parts.append(
        "<footer>\n<p>Generated by <code>tools/build-gallery.py</code> from "
        "whatever <code>docs/media</code> holds, so this page cannot claim an "
        "image that is not there. <strong>Copal Linux</strong> — MIT.</p>\n"
        "</footer>\n</main>\n")

    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"build-gallery: {len(ordered)} item(s) -> {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
