#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 paulr@sdf.org -- part of Copal Linux.
#
# copal-app-gallery.py -- docs/app-gallery.md: one small picture of every
# program that opened a window on the bench, from the probe's gallery run.
#
#   tools/copal-app-probe.sh --gallery docs/img/gallery NAME [CMD...]  # per program
#   tools/copal-app-gallery.py                                         # the document
#
# Pictures are what the probe left in docs/img/gallery (quarter-size JPEGs,
# 3-8 KB each); verdicts are the latest line per name in ~/copal-apps/log.txt.
# A program is "working" here if its latest probe found a window: ok, or a
# first-run page (WIZARD), which is still the program on screen. Programs
# that produced no window are listed at the end without a picture.
import os, re, sys, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.expanduser("~/copal-apps/log.txt")
GAL = os.path.join(ROOT, "docs", "img", "gallery")
EXTRAS = [  # name in the log/gallery, label, section
    ("kicad", "KiCad", "Engineering"), ("kmail", "KMail", "Mail"), ("brave", "Brave (Flatpak)", "Internet"),
    ("x64sc", "VICE x64sc", "Retro"), ("winebox-notepad++", "Notepad++ in a Wine box", "Windows"),
    ("endless-sky", "Endless Sky (built from source)", "Games"), ("wxmaxima", "wxMaxima (built from source)", "Science"),
    ("ytq", "ytq download queue", "Media"), ("streamripper", "streamripper (built from source)", "Radio"),
    ("winecfg", "winecfg", "Windows"),
]


def catalogue():
    rows = []
    with open(os.path.join(ROOT, "copal-prep.sh")) as f:
        for line in f:
            p = line.rstrip("\n").split("|")
            if len(p) == 6 and re.match(r"^[A-Z][a-z]+$", p[0]) and p[4] in ("x", "t"):
                rows.append(dict(section=p[0], label=p[1], bin=p[3], mode=p[4]))
    return rows


def verdicts():
    v = {}
    try:
        for line in open(LOG):
            m = re.match(r"^(\d\d:\d\d)\s+(\S+)\s+(.*)$", line.rstrip("\n"))
            if m and not line.startswith("==="):
                v[m.group(2)] = m.group(3).strip()
    except OSError:
        pass
    return v


def main():
    v = verdicts()
    rows = catalogue()
    seen = {r["bin"] for r in rows}
    for name, label, section in EXTRAS:
        if name not in seen:
            rows.append(dict(section=section, label=label, bin=name, mode="x"))
    by_section = {}
    missing = []
    for r in rows:
        verdict = v.get(r["bin"], "")
        pic = os.path.join(GAL, r["bin"] + ".jpg")
        if os.path.exists(pic) and (verdict.startswith("ok") or verdict.startswith("WIZARD")):
            by_section.setdefault(r["section"], []).append((r, verdict, os.path.getsize(pic)))
        elif verdict:
            missing.append((r, verdict))
    out = ["# The Copal Application Gallery: Every Program That Opened a Window, at a Glance\n",
           "<!-- SPDX-License-Identifier: MIT -->\n<!-- generated by tools/copal-app-gallery.py from ~/copal-apps/log.txt and docs/img/gallery -->",
           "Copyright (c) 2026 paulr@sdf.org. MIT licensed — see `LICENSE`.\n\n---\n",
           "Every picture is the bench's whole screen on workspace 2 at a quarter of its",
           "size, with every window the program opened moved there first, saved as a",
           "hard-compressed JPEG. Terminal programs run inside `foot`. The verdict line",
           "is the launch probe's (`tools/copal-app-probe.sh --gallery`). The bench is",
           "an aarch64 Copal guest under UTM with software OpenGL and, at the time of",
           "these pictures, no sound card — so anything that plays sound was silent.\n"]
    total = sum(len(x) for x in by_section.values())
    total_bytes = sum(b for x in by_section.values() for _, _, b in x)
    out.append("**%d programs pictured, %.1f MB of pictures.**\n" % (total, total_bytes / 1e6))
    for section in sorted(by_section):
        items = sorted(by_section[section], key=lambda t: t[0]["label"].lower())
        out.append("\n## %s (%d)\n" % (section, len(items)))
        out.append("| | | |\n|---|---|---|")
        cells = []
        for r, verdict, size in items:
            how = "terminal" if r["mode"] == "t" else "graphical"
            short = verdict.split("stderr")[0].strip()
            cells.append("![%s](img/gallery/%s.jpg)<br>**%s**<br>`%s` · %s · %s" % (
                r["label"].replace("|", "/"), r["bin"], r["label"].replace("|", "/"), r["bin"], how, short))
        for i in range(0, len(cells), 3):
            row = cells[i:i + 3] + [""] * (3 - len(cells[i:i + 3]))
            out.append("| " + " | ".join(row) + " |")
    if missing:
        out.append("\n## No window on this bench (%d)\n" % len(missing))
        out.append("| Program | Command | Verdict |\n|---|---|---|")
        for r, verdict in sorted(missing, key=lambda t: t[0]["label"].lower()):
            out.append("| %s | `%s` | %s |" % (r["label"].replace("|", "/"), r["bin"], verdict.split("stderr")[0].strip().replace("|", "/")))
    out.append("\n*Generated %s.*\n" % time.strftime("%Y-%m-%d %H:%M"))
    with open(os.path.join(ROOT, "docs", "app-gallery.md"), "w") as f:
        f.write("\n".join(out))
    print("docs/app-gallery.md: %d pictured, %d without a window, %.1f MB" % (total, len(missing), total_bytes / 1e6))


if __name__ == "__main__":
    main()
